version: '2'

services:
  loadbalancer:
    image: jwilder/nginx-proxy
    container_name: loadbalancer_trollface
    ports:
      - "8080:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  
  trollface1:
    image: tlc_test:latest
    container_name: trollface_1
    environment:
      - VIRTUAL_HOST=m
    restart: unless-stopped
    
  trollface2:
    image: tlc_test:latest
    container_name: trollface_2
    environment:
      - VIRTUAL_HOST=m
    restart: unless-stopped

  trollface3:
    image: tlc_test:latest
    container_name: trollface_3
    environment:
      - VIRTUAL_HOST=m
    restart: unless-stopped
  
  trolleface4:
    image: tlc_test:latest
    container_name: trolleface_4
    environment:
      - VIRTUAL_HOST=m
    restart: unless-stopped
    